# Generated by Django 2.1.5 on 2019-06-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль в группе (инструменты)'),
        ),
    ]
