# Generated by Django 2.1.5 on 2019-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0002_auto_20190606_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ManyToManyField(through='lotlinfoarchive.MusicianPhoto', to='lotlinfoarchive.Photo', verbose_name='Фотографии'),
        ),
    ]
