# Generated by Django 2.1.5 on 2019-07-14 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0003_auto_20190702_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(through='lotlinfoarchive.TrackInAlbum', to='lotlinfoarchive.Track', verbose_name='Треки в альбоме'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmaterial',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolink',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор ссылки '),
            preserve_default=False,
        ),
    ]
