# Generated by Django 2.1.5 on 2019-07-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0004_auto_20190714_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='slug',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически по заголовку. В случае неуникальности добавить в конце цифру', unique=True, verbose_name='Идентификатор ссылки '),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически по заголовку. В случае неуникальности добавить в конце цифру', unique=True, verbose_name='Идентификатор ссылки '),
        ),
        migrations.AlterField(
            model_name='musician',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически по заголовку. В случае неуникальности добавить в конце цифру', unique=True, verbose_name='Идентификатор ссылки '),
        ),
        migrations.AlterField(
            model_name='textmaterial',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически по заголовку. В случае неуникальности добавить в конце цифру', unique=True, verbose_name='Идентификатор ссылки '),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически по заголовку. В случае неуникальности добавить в конце цифру', unique=True, verbose_name='Идентификатор ссылки '),
        ),
    ]
