# Generated by Django 2.1.5 on 2019-08-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0005_auto_20190714_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Видео к тексту',
                'verbose_name_plural': 'Видео к тексту',
            },
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='videos',
        ),
        migrations.AlterField(
            model_name='phototext',
            name='text_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotlinfoarchive.TextMaterial', verbose_name='Текстовый материал'),
        ),
        migrations.AlterField(
            model_name='textmaterial',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotlinfoarchive.LotlTeamMember', verbose_name='Переводчик'),
        ),
        migrations.AddField(
            model_name='videotext',
            name='text_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotlinfoarchive.TextMaterial', verbose_name='Текстовый материал'),
        ),
        migrations.AddField(
            model_name='videotext',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotlinfoarchive.VideoLink', verbose_name='Видео к тексту'),
        ),
    ]
