# Generated by Django 2.1.5 on 2019-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0006_auto_20190805_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmaterial',
            name='videos',
            field=models.ManyToManyField(through='lotlinfoarchive.VideoText', to='lotlinfoarchive.VideoLink', verbose_name='Видео к материалу'),
        ),
    ]
