# Generated by Django 2.1.5 on 2019-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0007_textmaterial_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Для отображения в даминке (в основном', max_length=255, verbose_name='Заголовое')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текстовый блок информации')),
                ('template_name', models.CharField(blank=True, help_text='вместе с .html', max_length=255, null=True, verbose_name='Название темплейта в котором испольуется ')),
            ],
            options={
                'verbose_name': 'Текстовый блок информационной страницы',
                'verbose_name_plural': 'Текстовые блоки для информационных страниц',
            },
        ),
    ]
