# Generated by Django 2.1.5 on 2019-08-11 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0008_textinfoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='oover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotlinfoarchive.Photo', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='signature',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Автограф'),
        ),
        migrations.AlterField(
            model_name='textinfoblock',
            name='template_name',
            field=models.CharField(blank=True, default='', help_text='вместе с .html', max_length=255, null=True, verbose_name='Название темплейта в котором испольуется '),
        ),
    ]
