# Generated by Django 2.1.5 on 2019-08-11 18:09

from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0009_auto_20190811_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='associated_tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ассоциированные теги'),
        ),
        migrations.AlterField(
            model_name='album',
            name='buy_links',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.BuyLink', verbose_name='Ссылки на покупку альбома'),
        ),
        migrations.AlterField(
            model_name='album',
            name='oover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotlinfoarchive.Photo', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotlinfoarchive.Tour', verbose_name='Тур в поддержку альбома'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='lotlinfoarchive.TrackInAlbum', to='lotlinfoarchive.Track', verbose_name='Треки в альбоме'),
        ),
    ]
