# Generated by Django 2.1.5 on 2019-10-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0011_auto_20191003_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_full_de',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_full_en',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_full_ru',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_short_de',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_short_en',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='text_short_ru',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='title_ru',
        ),
    ]
