# Generated by Django 2.1.5 on 2019-10-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0014_auto_20191003_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='photoevent',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='lotlinfoarchive.Photo', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='event',
            name='site_photos',
            field=models.ManyToManyField(blank=True, related_name='site_event_photos', to='lotlinfoarchive.Photo', verbose_name='Фото к материалу'),
        ),
        migrations.AlterField(
            model_name='buylink',
            name='source',
            field=models.CharField(choices=[('0', 'Lord Of The Lost Online Shop'), ('1', 'iTunes'), ('2', 'Eventim.de'), ('3', 'Другoе')], default='0', max_length=1, verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='articles',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.Article', verbose_name='Статьи по событию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='news',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.News', verbose_name='Новости по событию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.BuyLink', verbose_name='Ссылки на покупку билетов'),
        ),
        migrations.AlterField(
            model_name='event',
            name='videos',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.VideoLink', verbose_name='Видео к событию'),
        ),
        migrations.DeleteModel(
            name='PhotoEvent',
        ),
    ]
