# Generated by Django 2.1.5 on 2019-10-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0015_auto_20191029_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototext',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='phototext',
            name='text_material',
        ),
        migrations.RemoveField(
            model_name='videotext',
            name='text_material',
        ),
        migrations.RemoveField(
            model_name='videotext',
            name='video',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='textmaterial',
            name='videos',
        ),
        migrations.AddField(
            model_name='textmaterial',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_cover', to='lotlinfoarchive.Photo', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='textmaterial',
            name='site_photos',
            field=models.ManyToManyField(related_name='site_text_photoes', to='lotlinfoarchive.Photo', verbose_name='Фото к материалу'),
        ),
        migrations.AddField(
            model_name='textmaterial',
            name='videos_urls',
            field=models.ManyToManyField(to='lotlinfoarchive.VideoLink', verbose_name='Видео к материалу'),
        ),
        migrations.DeleteModel(
            name='PhotoText',
        ),
        migrations.DeleteModel(
            name='VideoText',
        ),
    ]
