# Generated by Django 2.1.5 on 2019-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlinfoarchive', '0016_auto_20191030_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реальное имя'),
        ),
        migrations.AlterField(
            model_name='textmaterial',
            name='site_photos',
            field=models.ManyToManyField(blank=True, related_name='site_text_photoes', to='lotlinfoarchive.Photo', verbose_name='Фото к материалу'),
        ),
        migrations.AlterField(
            model_name='textmaterial',
            name='videos_urls',
            field=models.ManyToManyField(blank=True, to='lotlinfoarchive.VideoLink', verbose_name='Видео к материалу'),
        ),
    ]
