# Generated by Django 2.1.5 on 2019-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_dev_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='body_text_de',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='body_text_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
