# Generated by Django 2.1.5 on 2019-01-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_dev_tests', '0002_auto_20190128_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='body_text_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
