# Generated by Django 2.1.5 on 2019-05-26 17:14

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('for_dev_tests', '0004_simpletranslationmodel_test_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletranslationmodel',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
